# Configurações da aplicação Quarkus
# Configuração do banner da aplicação
quarkus.banner.enabled=true

# Configuração do endpoint de métricas (já incluído via micrometer)
quarkus.micrometer.enabled=true
quarkus.micrometer.registry-enabled-default=true
